package com.minecolonies.coremod.client.model.raiders;

import com.minecolonies.api.client.render.modeltype.EgyptianModel;
import com.minecolonies.api.entity.mobs.egyptians.AbstractEntityEgyptian;
import net.minecraft.client.renderer.model.ModelRenderer;

/**
 * ModelPharaohMummy.
 * Created using Tabula 7.0.0
 */
public class ModelPharaoh extends EgyptianModel<AbstractEntityEgyptian>
{
    public ModelPharaoh()
    {
        ModelRenderer armRightLayer;
        ModelRenderer legRightPant;
        ModelRenderer legRightLayer;
        ModelRenderer bodyCollar;
        ModelRenderer bodyBottom;
        ModelRenderer bodyJewel;
        ModelRenderer bodyGoldenStrip;
        ModelRenderer bodyLayer;
        ModelRenderer armLeftLayer;
        ModelRenderer legLeftPant;
        ModelRenderer legLeftLayer;
        ModelRenderer snakeBody;
        ModelRenderer snakeHead;
        ModelRenderer headLeftSideTop;
        ModelRenderer headLeftSideMiddle;
        ModelRenderer headLeftSideBottom;
        ModelRenderer headRightSideTop;
        ModelRenderer headRightSideMiddle;
        ModelRenderer headTail;
        ModelRenderer headTop;
        ModelRenderer headRightSideBottom;
        ModelRenderer headCap;
        ModelRenderer headHat;
        ModelRenderer headBack;
        ModelRenderer headBackCap;
        ModelRenderer jaw;
        ModelRenderer TeethTopFront;
        ModelRenderer TeethTopRight;
        ModelRenderer TeethTopLeft;
        ModelRenderer TeethBottomFront;
        ModelRenderer TeethBottomRight;
        ModelRenderer TeethBottomLeft;
        
        textureWidth = 128;
        textureHeight = 64;
        headBackCap = new ModelRenderer(this, 14, 59);
        headBackCap.setRotationPoint(0.0F, 0.0F, 0.92F);
        headBackCap.addBox(-4.5F, -2.85F, 0.0F, 9, 3, 0, 0.0F);
        bipedRightArm = new ModelRenderer(this, 40, 16);
        bipedRightArm.setRotationPoint(-5.0F, 2.0F, 0.0F);
        bipedRightArm.addBox(-3.0F, -2.0F, -2.0F, 4, 12, 4, 0.0F);
        TeethBottomFront = new ModelRenderer(this, 0, 15);
        TeethBottomFront.setRotationPoint(0.0F, 0.0F, 0.0F);
        TeethBottomFront.addBox(-2.5F, 0.0F, -4.0F, 5, 1, 0, 0.0F);
        headRightSideMiddle = new ModelRenderer(this, 14, 51);
        headRightSideMiddle.setRotationPoint(-7.82F, -7.11F, 0.86F);
        headRightSideMiddle.addBox(0.0F, 0.0F, 0.19F, 5, 6, 2, 0.14F);
        setRotateAngle(headRightSideMiddle, 0.0F, 0.0F, 0.26878070480712674F);
        bodyLayer = new ModelRenderer(this, 0, 32);
        bodyLayer.setRotationPoint(0.0F, 0.0F, 0.0F);
        bodyLayer.addBox(-4.0F, 0.0F, -2.0F, 8, 12, 4, 0.3F);
        bodyCollar = new ModelRenderer(this, 44, 0);
        bodyCollar.setRotationPoint(0.0F, 0.0F, 0.0F);
        bodyCollar.addBox(-5.5F, -0.2F, -2.5F, 11, 5, 5, 0.1F);
        TeethBottomRight = new ModelRenderer(this, 10, 11);
        TeethBottomRight.setRotationPoint(0.0F, 0.0F, 0.0F);
        TeethBottomRight.addBox(-2.5F, 0.0F, -4.0F, 0, 1, 4, 0.0F);
        legLeftPant = new ModelRenderer(this, 56, 20);
        legLeftPant.mirror = true;
        legLeftPant.setRotationPoint(0.0F, 0.0F, 0.0F);
        legLeftPant.addBox(-2.4F, -0.5F, -2.5F, 5, 6, 5, 0.0F);
        bipedRightLeg = new ModelRenderer(this, 24, 16);
        bipedRightLeg.setRotationPoint(-1.9F, 12.0F, 0.1F);
        bipedRightLeg.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4, 0.0F);
        jaw = new ModelRenderer(this, 33, 54);
        jaw.setRotationPoint(0.0F, -2.0F, 0.0F);
        jaw.addBox(-2.5F, 1.0F, -4.0F, 5, 1, 5, 0.0F);
        setRotateAngle(jaw, 0.5462880558742251F, 0.0F, 0.0F);
        bipedBody = new ModelRenderer(this, 0, 16);
        bipedBody.setRotationPoint(0.0F, 0.0F, 0.0F);
        bipedBody.addBox(-4.0F, 0.0F, -2.0F, 8, 12, 4, 0.0F);
        headTail = new ModelRenderer(this, 28, 51);
        headTail.setRotationPoint(-1.5F, 0.4F, 2.5F);
        headTail.addBox(0.0F, 0.0F, 0.0F, 3, 6, 2, -0.2F);
        armRightLayer = new ModelRenderer(this, 40, 32);
        armRightLayer.setRotationPoint(0.0F, 0.0F, 0.0F);
        armRightLayer.addBox(-3.0F, -2.0F, -2.0F, 4, 12, 4, 0.3F);
        headBack = new ModelRenderer(this, 38, 48);
        headBack.setRotationPoint(0.0F, 0.0F, 0.0F);
        headBack.addBox(-3.0F, -2.0F, 0.0F, 6, 2, 4, 0.0F);
        armLeftLayer = new ModelRenderer(this, 24, 32);
        armLeftLayer.mirror = true;
        armLeftLayer.setRotationPoint(0.0F, 0.0F, 0.0F);
        armLeftLayer.addBox(-1.0F, -2.0F, -2.0F, 4, 12, 4, 0.3F);
        legLeftLayer = new ModelRenderer(this, 40, 32);
        legLeftLayer.mirror = true;
        legLeftLayer.setRotationPoint(0.0F, 0.0F, 0.0F);
        legLeftLayer.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4, 0.2F);
        headRightSideBottom = new ModelRenderer(this, 0, 57);
        headRightSideBottom.setRotationPoint(-9.58F, -1.23F, 0.91F);
        headRightSideBottom.addBox(0.0F, -1.0F, -4.0F, 3, 1, 4, 0.0F);
        setRotateAngle(headRightSideBottom, 0.0F, -0.9147270609702279F, 0.26878070480712674F);
        headLeftSideBottom = new ModelRenderer(this, 0, 57);
        headLeftSideBottom.mirror = true;
        headLeftSideBottom.setRotationPoint(9.58F, -1.23F, 0.91F);
        headLeftSideBottom.addBox(-3.0F, -1.0F, -4.0F, 3, 1, 4, 0.0F);
        setRotateAngle(headLeftSideBottom, 0.0F, 0.9147270609702279F, -0.26878070480712674F);
        snakeHead = new ModelRenderer(this, 77, 3);
        snakeHead.setRotationPoint(0.0F, -10.65F, -4.5F);
        snakeHead.addBox(-1.5F, -1.0F, -2.0F, 3, 3, 3, -0.99F);
        setRotateAngle(snakeHead, 0.2792526803190927F, 0.0F, 0.0F);
        headCap = new ModelRenderer(this, 18, 49);
        headCap.setRotationPoint(0.0F, -11.4F, 0.85F);
        headCap.addBox(-4.5F, 0.15F, 0.19F, 9, 0, 2, 0.13F);
        headLeftSideMiddle = new ModelRenderer(this, 14, 51);
        headLeftSideMiddle.mirror = true;
        headLeftSideMiddle.setRotationPoint(7.82F, -7.11F, 0.86F);
        headLeftSideMiddle.addBox(-5.0F, 0.0F, 0.19F, 5, 6, 2, 0.14F);
        setRotateAngle(headLeftSideMiddle, 0.0F, 0.0F, -0.26878070480712674F);
        bipedLeftArm = new ModelRenderer(this, 24, 16);
        bipedLeftArm.mirror = true;
        bipedLeftArm.setRotationPoint(5.0F, 2.0F, 0.0F);
        bipedLeftArm.addBox(-1.0F, -2.0F, -2.0F, 4, 12, 4, 0.0F);
        legRightLayer = new ModelRenderer(this, 24, 32);
        legRightLayer.setRotationPoint(0.0F, 0.0F, 0.0F);
        legRightLayer.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4, 0.2F);
        bodyBottom = new ModelRenderer(this, 52, 11);
        bodyBottom.setRotationPoint(0.0F, 0.0F, 0.0F);
        bodyBottom.addBox(-4.5F, 8.5F, -2.5F, 9, 4, 5, 0.0F);
        headHat = new ModelRenderer(this, 80, 0);
        headHat.setRotationPoint(0.0F, 0.0F, 0.0F);
        headHat.addBox(-4.5F, -8.5F, -4.5F, 9, 9, 9, 0.1F);
        headRightSideTop = new ModelRenderer(this, 0, 51);
        headRightSideTop.setRotationPoint(-4.6F, -11.4F, 0.86F);
        headRightSideTop.addBox(-5.15F, 0.13F, 0.19F, 5, 4, 2, 0.13F);
        setRotateAngle(headRightSideTop, 0.0F, 0.0F, -0.890117918517108F);
        bodyJewel = new ModelRenderer(this, 0, 0);
        bodyJewel.setRotationPoint(0.0F, 10.0F, -2.0F);
        bodyJewel.addBox(-1.5F, -1.5F, -1.0F, 3, 3, 1, -0.3F);
        setRotateAngle(bodyJewel, 0.0F, 0.0F, 0.7853981633974483F);
        bipedLeftLeg = new ModelRenderer(this, 40, 16);
        bipedLeftLeg.mirror = true;
        bipedLeftLeg.setRotationPoint(1.9F, 12.0F, 0.1F);
        bipedLeftLeg.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4, 0.0F);
        headTop = new ModelRenderer(this, 76, 18);
        headTop.setRotationPoint(0.0F, -8.55F, -4.45F);
        headTop.addBox(-4.5F, 0.0F, 0.0F, 9, 4, 8, 0.09F);
        setRotateAngle(headTop, 0.4714134309636684F, 0.0F, 0.0F);
        TeethTopLeft = new ModelRenderer(this, 10, 10);
        TeethTopLeft.setRotationPoint(0.0F, 0.0F, 0.0F);
        TeethTopLeft.addBox(2.5F, -2.0F, -3.5F, 0, 1, 4, 0.0F);
        snakeBody = new ModelRenderer(this, 76, 2);
        snakeBody.setRotationPoint(0.0F, -7.5F, -4.6F);
        snakeBody.addBox(-0.5F, -3.0F, -1.0F, 1, 3, 1, 0.0F);
        setRotateAngle(snakeBody, -0.3490658503988659F, 0.0F, 0.0F);
        legRightPant = new ModelRenderer(this, 56, 20);
        legRightPant.setRotationPoint(0.0F, 0.0F, 0.0F);
        legRightPant.addBox(-2.6F, -0.5F, -2.5F, 5, 6, 5, 0.0F);
        bodyGoldenStrip = new ModelRenderer(this, 38, 12);
        bodyGoldenStrip.setRotationPoint(0.0F, 10.0F, -2.6F);
        bodyGoldenStrip.addBox(-1.5F, 0.0F, 0.0F, 3, 8, 0, 0.0F);
        TeethTopFront = new ModelRenderer(this, 0, 14);
        TeethTopFront.setRotationPoint(0.0F, 0.0F, 0.0F);
        TeethTopFront.addBox(-2.5F, -2.0F, -3.5F, 5, 1, 0, 0.0F);
        bipedHead = new ModelRenderer(this, 0, 0);
        bipedHead.setRotationPoint(0.0F, 0.0F, -1.0F);
        bipedHead.addBox(-4.0F, -8.0F, -4.0F, 8, 6, 8, 0.0F);
        headLeftSideTop = new ModelRenderer(this, 0, 51);
        headLeftSideTop.mirror = true;
        headLeftSideTop.setRotationPoint(4.6F, -11.4F, 0.86F);
        headLeftSideTop.addBox(0.15F, 0.13F, 0.19F, 5, 4, 2, 0.13F);
        setRotateAngle(headLeftSideTop, 0.0F, 0.0F, 0.890117918517108F);
        TeethBottomLeft = new ModelRenderer(this, 10, 11);
        TeethBottomLeft.setRotationPoint(0.0F, 0.0F, 0.0F);
        TeethBottomLeft.addBox(2.5F, 0.0F, -4.0F, 0, 1, 4, 0.0F);
        TeethTopRight = new ModelRenderer(this, 10, 10);
        TeethTopRight.setRotationPoint(0.0F, 0.0F, 0.0F);
        TeethTopRight.addBox(-2.5F, -2.0F, -3.5F, 0, 1, 4, 0.0F);
        bipedHead.addChild(headBackCap);
        jaw.addChild(TeethBottomFront);
        bipedHead.addChild(headRightSideMiddle);
        bipedBody.addChild(bodyLayer);
        bipedBody.addChild(bodyCollar);
        jaw.addChild(TeethBottomRight);
        bipedLeftLeg.addChild(legLeftPant);
        bipedHead.addChild(jaw);
        bipedHead.addChild(headTail);
        bipedRightArm.addChild(armRightLayer);
        bipedHead.addChild(headBack);
        bipedLeftArm.addChild(armLeftLayer);
        bipedLeftLeg.addChild(legLeftLayer);
        bipedHead.addChild(headRightSideBottom);
        bipedHead.addChild(headLeftSideBottom);
        bipedHead.addChild(snakeHead);
        bipedHead.addChild(headCap);
        bipedHead.addChild(headLeftSideMiddle);
        bipedRightLeg.addChild(legRightLayer);
        bipedBody.addChild(bodyBottom);
        bipedHead.addChild(headHat);
        bipedHead.addChild(headRightSideTop);
        bipedBody.addChild(bodyJewel);
        bipedHead.addChild(headTop);
        bipedHead.addChild(TeethTopLeft);
        bipedHead.addChild(snakeBody);
        bipedRightLeg.addChild(legRightPant);
        bipedBody.addChild(bodyGoldenStrip);
        bipedHead.addChild(TeethTopFront);
        bipedHead.addChild(headLeftSideTop);
        jaw.addChild(TeethBottomLeft);
        bipedHead.addChild(TeethTopRight);
    }

    /**
     * This is a helper function from Tabula to set the rotation of model parts
     */
    public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z)
    {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }
}
