package com.minecolonies.coremod.configuration;

public class Configurations
{
    public static final int     CITIZEN_RESPAWN_INTERVAL_MIN = 10;
    public static final int     CITIZEN_RESPAWN_INTERVAL_MAX = 600;
    public static       int     workingRangeTownHall         = 100;
    public static       int     townHallPadding              = 20;
    public static       boolean supplyChests                 = true;
    public static       boolean allowInfiniteSupplyChests    = false;
    public static       int     citizenRespawnInterval       = 30;
    public static       boolean builderInfiniteResources     = false;
    public static       int     builderBuildBlockDelay       = 0;
    public static       int     blockMiningDelayModifier     = 1000;

    public static boolean enableColonyProtection = true;
    public static boolean turnOffExplosionsInColonies = true;

    //TODO change to false when material handling is implemented
    public static boolean deliverymanInfiniteResources = true;

    //TODO remove config value and set maxCitizens based on the colony buildings/levels
    public static int     maxCitizens         = 4;
    public static boolean alwaysRenderNameTag = true;

    //TODO change count to agreed upon value, possibly remove if we think this shouldn't be a problem
    public static int maxBlocksCheckedByBuilder = 1000;
    public static int chatFrequency             = 30;

    public static boolean enableInDevelopmentFeatures = false;

    public static boolean pathfindingDebugDraw      = false;
    public static int     pathfindingDebugVerbosity = 0;
    public static int     pathfindingMaxThreadCount = 2;

    public static String[] maleFirstNames = new String[]
                                              {
                                                  "Abraham",
                                                  "Adam",
                                                  "Adrian",
                                                  "Alexander",
                                                  "Allen",
                                                  "Ambrose",
                                                  "Andrew",
                                                  "Anthony",
                                                  "Arthur",
                                                  "Avery",
                                                  "Barnaby",
                                                  "Bartholomew",
                                                  "Benedict",
                                                  "Bernard",
                                                  "Charles",
                                                  "Christopher",
                                                  "Cuthbert",
                                                  "Daniel",
                                                  "David",
                                                  "Edmund",
                                                  "Edward",
                                                  "Francis",
                                                  "Fulke",
                                                  "Geoffrey",
                                                  "George",
                                                  "Gerard",
                                                  "Gilbert",
                                                  "Giles",
                                                  "Gregory",
                                                  "Henry",
                                                  "Hugh",
                                                  "Humphrey",
                                                  "Isaac",
                                                  "James",
                                                  "Jerome",
                                                  "John",
                                                  "Joseph",
                                                  "Julian",
                                                  "Lancelot",
                                                  "Lawrence",
                                                  "Leonard",
                                                  "Luke",
                                                  "Mark",
                                                  "Martin",
                                                  "Mathias",
                                                  "Matthew",
                                                  "Michael",
                                                  "Miles",
                                                  "Nathaniel",
                                                  "Nicholas",
                                                  "Oliver",
                                                  "Oswyn",
                                                  "Peter",
                                                  "Philip",
                                                  "Piers",
                                                  "Ralph",
                                                  "Reynold",
                                                  "Richard",
                                                  "Robert",
                                                  "Roger",
                                                  "Rowland",
                                                  "Samuel",
                                                  "Simon",
                                                  "Solomon",
                                                  "Stephen",
                                                  "Thomas",
                                                  "Tobias",
                                                  "Walter",
                                                  "William"
                                              };

    public static String[] femaleFirstNames = new String[]
                                                {
                                                  "Agnes",
                                                  "Alice",
                                                  "Amy",
                                                  "Anne",
                                                  "Audrey",
                                                  "Avis",
                                                  "Barbara",
                                                  "Beatrice",
                                                  "Betty",
                                                  "Blanche",
                                                  "Bridget",
                                                  "Catherine",
                                                  "Cecily",
                                                  "Charity",
                                                  "Christian",
                                                  "Christina",
                                                  "Clemence",
                                                  "Constance",
                                                  "Denise",
                                                  "Dorothy",
                                                  "Edith",
                                                  "Elinor",
                                                  "Elizabeth",
                                                  "Ellen",
                                                  "Emma",
                                                  "Florence",
                                                  "Fortune",
                                                  "Frances",
                                                  "Frideswide",
                                                  "Gillian",
                                                  "Grace",
                                                  "Helen",
                                                  "Isabel",
                                                  "Jane",
                                                  "Janet",
                                                  "Jennifer",
                                                  "Joan",
                                                  "Josian",
                                                  "Joyce",
                                                  "Judith",
                                                  "Karen",
                                                  "Katherine",
                                                  "Lettice",
                                                  "Linda",
                                                  "Lisa",
                                                  "Lucy",
                                                  "Mabel",
                                                  "Margaret",
                                                  "Margery",
                                                  "Maria",
                                                  "Marion",
                                                  "Martha",
                                                  "Mary",
                                                  "Maud",
                                                  "Mildred",
                                                  "Millicent",
                                                  "Nancy",
                                                  "Natasha",
                                                  "Parnell",
                                                  "Philippa",
                                                  "Rachel",
                                                  "Rebecca",
                                                  "Rose",
                                                  "Ruth",
                                                  "Sarah",
                                                  "Susan",
                                                  "Susanna",
                                                  "Sybil",
                                                  "Thomasin",
                                                  "Ursula",
                                                  "Wilmot",
                                                  "Winifred"
                                                };

    public static String[] lastNames = new String[]
                                         {
                                           "Abell",
                                           "Ackworth",
                                           "Adams",
                                           "Addicock",
                                           "Alban",
                                           "Aldebourne",
                                           "Alfray",
                                           "Alicock",
                                           "Allard",
                                           "Allen",
                                           "Allington",
                                           "Amberden",
                                           "Amcotts",
                                           "Amondsham",
                                           "Andrews",
                                           "Annesley",
                                           "Ansty",
                                           "Archer",
                                           "Ardall",
                                           "Ardern",
                                           "Argentein",
                                           "Arnold",
                                           "Arthur",
                                           "Asger",
                                           "Ashby",
                                           "Ashcombe",
                                           "Ashenhurst",
                                           "Ashton",
                                           "Askew",
                                           "Asplin",
                                           "Astley",
                                           "Atherton",
                                           "Atkinson",
                                           "Atlee",
                                           "Attilburgh",
                                           "Aubrey",
                                           "Audeley",
                                           "Audlington",
                                           "Ayde",
                                           "Ayleward",
                                           "Aylmer",
                                           "Aynesworth",
                                           "Babham",
                                           "Babington",
                                           "Badby",
                                           "Bailey",
                                           "Baker",
                                           "Balam",
                                           "Baldwin",
                                           "Ballard",
                                           "Ballett",
                                           "Bammard",
                                           "Barber",
                                           "Bardolf",
                                           "Barefoot",
                                           "Barker",
                                           "Barnes",
                                           "Barre",
                                           "Barrentine",
                                           "Barrett",
                                           "Barstaple",
                                           "Bartelot",
                                           "Barton",
                                           "Basset",
                                           "Bathurst",
                                           "Battersby",
                                           "Battle",
                                           "Baynton",
                                           "Beauchamp",
                                           "Cheddar",
                                           "Chelsey",
                                           "Chernock",
                                           "Chester",
                                           "Chetwood",
                                           "Cheverell",
                                           "Cheyne",
                                           "Chichester",
                                           "Child",
                                           "Chilton",
                                           "Chowne",
                                           "Chudderley",
                                           "Church",
                                           "Churmond",
                                           "Clark",
                                           "Clavell",
                                           "Claybrook",
                                           "Clement",
                                           "Clerk",
                                           "Clifford",
                                           "Clifton",
                                           "Clitherow",
                                           "Clopton",
                                           "Cobb",
                                           "Cobham",
                                           "Cobley",
                                           "Cockayne",
                                           "Cod",
                                           "Coddington",
                                           "Coffin",
                                           "Coggshall",
                                           "Colby",
                                           "Cole",
                                           "Colkins",
                                           "Collard",
                                           "Colmer",
                                           "Colt",
                                           "Colthurst",
                                           "Complin",
                                           "Compton",
                                           "Conquest",
                                           "Cooke",
                                           "Coorthopp",
                                           "Coppinger",
                                           "Corbett",
                                           "Corby",
                                           "Cossington",
                                           "Cosworth",
                                           "Cotton",
                                           "Courtenay",
                                           "Covert",
                                           "Cowill",
                                           "Cox",
                                           "Crane",
                                           "Cranford",
                                           "Crawley",
                                           "Cressy",
                                           "Crickett",
                                           "Cripps",
                                           "Crisp",
                                           "Cristemas",
                                           "Crocker",
                                           "Crugg",
                                           "Cuddon",
                                           "Culpepper",
                                           "Cunningham",
                                           "Curtis",
                                           "Curzon",
                                           "Dagworth",
                                           "Gardiner",
                                           "Gare",
                                           "Garnis",
                                           "Garrard",
                                           "Garret",
                                           "Gascoigne",
                                           "Gasper",
                                           "Gavell",
                                           "Gedding",
                                           "Geoffrey",
                                           "George",
                                           "Gerard",
                                           "Gerville",
                                           "Geste",
                                           "Gibbs",
                                           "Gifford",
                                           "Gilbert",
                                           "Gill",
                                           "Ginter",
                                           "Gisborne",
                                           "Gittens",
                                           "Glennon",
                                           "Glover",
                                           "Gobberd",
                                           "Goddam",
                                           "Godfrey",
                                           "Gold",
                                           "Golding",
                                           "Goldwell",
                                           "Gomershall",
                                           "Gomfrey",
                                           "Gonson",
                                           "Good",
                                           "Goodenouth",
                                           "Gooder",
                                           "Goodluck",
                                           "Goodnestone",
                                           "Goodrick",
                                           "Goodrington",
                                           "Goodwin",
                                           "Goring",
                                           "Gorney",
                                           "Gorst",
                                           "Gosebourne",
                                           "Grafton",
                                           "Gray",
                                           "Greene",
                                           "Greenway",
                                           "Grenefeld",
                                           "Greville",
                                           "Grey",
                                           "Grimbald",
                                           "Grobbam",
                                           "Grofhurst",
                                           "Groston",
                                           "Grove",
                                           "Guildford",
                                           "Hackman",
                                           "Haddock",
                                           "Haddon",
                                           "Hadresham",
                                           "Hakebourne",
                                           "Hale",
                                           "Hall",
                                           "Halley",
                                           "Hambard",
                                           "Hammer",
                                           "Hammond",
                                           "Hampden"
                                         };
}
