approve_by_comment: true
approve_regex: '^(Approved|:shipit:|:\+1:|LGTM)'
author_approval: required
reject_regex: ^Rejected
reset_on_push: true
reviewers:
  name: maintainers
  required: 3
  teams:
    - maintainers
