org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

modId=minecolonies
modGroup=com.ldtteam
local.version=0.0.1-local
modBaseName=minecolonies

javaVersion=25
useJavaToolChains=true

minecraft.version=26.2
minecraft.additionalVersions=
neoforge.version=26.2.0.66

fml_range=[11,)
neoforge_range=[26.2,)
minecraft_range=[26.2, 27)
blockUiRange=[0.0.1,)
domumOrnamentumRange=[1.0.0,)
structurizeRange=[0.0.1,)
usesMCVersionOrderFirst=true

githubUrl=https://github.com/ldtteam/Minecolonies
gitUrl=https://github.com/ldtteam/Minecolonies.git
gitConnectUrl=https://github.com/ldtteam/Minecolonies.git
projectUrl=https://www.curseforge.com/minecraft/mc-mods/minecolonies
curseId=245506
usesCurse=true
requiredCurseDependencies=structurize;domum-ornamentum;blockui;multi-piston;towntalk

usesCrowdin=true
usesCrowdInVersionSeparation=true
crowdinId=minecolonies
usesDatagen=true
useDefaultTestSystem=false
runtimeSourceSets=main
librarySourceSets=main;datagen;
projectHasApi=false
extendDefaultSourceSetConfiguration=true
mainExcludedResources=assets/minecolonies/lang/manual_en_us.json;assets/minecolonies/lang/default.json;assets/minecolonies/lang/quests.json
usesMergableTranslations=true
translationMergeSources[0]=src/main/resources/assets/minecolonies/lang/manual_en_us.json
translationMergeSources[1]=src/datagen/generated/minecolonies/assets/minecolonies/lang/default.json
translationMergeSources[2]=src/datagen/generated/minecolonies/assets/minecolonies/lang/tag.item.json
translationMergeSources[3]=src/datagen/generated/minecolonies/assets/minecolonies/lang/quests.json
translationMergeDestination[0]=src/main/resources/assets/minecolonies/lang/entries.json
translationMergeDestination[1]=src/main/resources/assets/minecolonies/lang/en_us.json
usesSonarQube=false
usesCrowdInTranslationManagement=true
crowdInDownloadDirectory=src/main/resources/assets/minecolonies/lang
usesCrowdInUploadWithFilteredBranchesSpec=(version|release)\/1\.21
additionalModsInDataGen=structurize;domum_ornamentum
