package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.schedule
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Branches_Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Branches_Build")) {
    triggers {
        add {
            schedule {
                id = "TRIGGER_11"
                schedulingPolicy = weekly {
                }
                triggerBuild = always()
            }
        }
    }
}
