package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'Alpha'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("Alpha")) {
    check(name == "Alpha") {
        "Unexpected name: '$name'"
    }
    name = "Beta"

    check(description == "Alpha version builds of minecolonies") {
        "Unexpected description: '$description'"
    }
    description = "Beta version builds of minecolonies"

    params {
        expect {
            param("env.CURSERELEASETYPE", "alpha")
        }
        update {
            param("env.CURSERELEASETYPE", "beta")
        }
        expect {
            param("env.Version.Suffix", "-ALPHA")
        }
        update {
            param("env.Version.Suffix", "-DETA")
        }
        expect {
            text("env.crowdinKey", "credentialsJSON:ce949f49-133c-4bb1-83d7-257c570d43aa", label = "Crowdin key", description = "The API key for crowdin to pull translations", allowEmpty = true)
        }
        update {
            text("env.crowdinKey", "credentialsJSON:47237e1a-13a7-4a4d-a644-431c2adee81c", label = "Crowdin key", description = "The API key for crowdin to pull translations", allowEmpty = true)
        }
    }
}
