package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'Branches'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("Branches")) {
    params {
        expect {
            param("VCS.Branches", """
                +:refs/heads/(*)
                -:refs/heads/version/*
                -:refs/heads/testing/*
                -:refs/heads/release/*
                -:refs/pull/*/head
                -:refs/heads/CI/*
            """.trimIndent())
        }
        update {
            param("VCS.Branches", """
                +:refs/heads/(*)
                -:refs/heads/version/*
                -:refs/heads/testing/*
                -:refs/heads/release/*
                -:refs/pull/*/head
                -:refs/heads/CI/*
                -:<default>
            """.trimIndent())
        }
    }
}
