package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'Release'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("Release")) {
    params {
        expect {
            param("VCS.Branches", "+:refs/heads/testing/(*)")
        }
        update {
            param("VCS.Branches", """
                +:refs/heads/release/(*)
                -:<default>
            """.trimIndent())
        }
        expect {
            text("env.crowdinKey", "credentialsJSON:57fbe4f4-13dd-4c72-b6b3-3cc1e3a8240e", label = "Crowdin key", description = "The API key for crowdin to pull translations", allowEmpty = true)
        }
        update {
            text("env.crowdinKey", "credentialsJSON:769784c9-3cf4-4647-b4c8-39d365a8a55a", label = "Crowdin key", description = "The API key for crowdin to pull translations", allowEmpty = true)
        }
    }
}
