package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'UpgradeAlphaBeta'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("UpgradeAlphaBeta")) {
    check(name == "Upgrade - Alpha -> Beta") {
        "Unexpected name: '$name'"
    }
    name = "Upgrade - Beta -> Release"

    check(description == "Updates the current alpha to beta.") {
        "Unexpected description: '$description'"
    }
    description = "Updates the current beta to release."
}
