repositories {
    mavenLocal()
    maven {
        name = 'LocalBlockUI'
        url = uri(rootProject.layout.projectDirectory.dir('../BlockUI/repo'))
    }
    maven {
        name = 'LocalDomumOrnamentum'
        url = uri(rootProject.layout.projectDirectory.dir('../Domum-Ornamentum/repo'))
    }
    maven {
        name = 'LocalStructurize'
        url = uri(rootProject.layout.projectDirectory.dir('../Structurize/repo'))
    }
    maven {
        name = 'LDTTeamModding'
        url = uri('https://ldtteam.jfrog.io/ldtteam/modding/')
    }
    maven {
        name = 'JourneyMap'
        url = uri('https://jm.gserv.me/repository/maven-public/')
    }
}

dependencies {
    implementation('com.ldtteam:domum-ornamentum:1.0.0-local')
    implementation('com.ldtteam:blockui:0.0.1-local')
    implementation('com.ldtteam:structurize:0.0.1-local')
    implementation('com.ldtteam:multipiston:0.0.1-local')
    implementation('com.dtteam.dynamictrees:dynamictrees-neoforge-26.2:1.8.0')

    compileOnly 'mezz.jei:jei-26.2-neoforge-api:30.25.0.177'
    runtimeOnly 'mezz.jei:jei-26.2-neoforge:30.25.0.177'

    compileOnly 'info.journeymap:journeymap-api-neoforge:26.2-2.0.0'

    testImplementation 'junit:junit:4.13.2'
}
