package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Configuration'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("Configuration")
    name = "Configuration"
    url = "https://github.com/ldtteam/minecolonies.git"
    branch = "version/main"
    authMethod = password {
        userName = "git"
        password = "credentialsJSON:0ab5d46b-ca88-4fa8-93d2-163fe135b15a"
    }
}))

