package com.minecolonies.api.colony.buildings;

import com.minecolonies.api.colony.buildings.registry.BuildingEntry;
import net.neoforged.neoforge.registries.DeferredHolder;

public final class ModBuildings
{

    public static final String ARCHERY_ID        = "archery";
    public static final String BAKERY_ID         = "baker";
    public static final String BARRACKS_ID       = "barracks";
    public static final String BARRACKS_TOWER_ID = "barrackstower";
    public static final String BLACKSMITH_ID     = "blacksmith";
    public static final String BUILDER_ID        = "builder";
    public static final String CHICKENHERDER_ID  = "chickenherder";
    public static final String COMBAT_ACADEMY_ID = "combatacademy";
    public static final String COMPOSTER_ID      = "composter";
    public static final String COOK_ID           = "cook";
    public static final String COWBOY_ID         = "cowboy";
    public static final String CRUSHER_ID        = "crusher";
    public static final String DELIVERYMAN_ID    = "deliveryman";
    public static final String FARMER_ID         = "farmer";
    public static final String FISHERMAN_ID      = "fisherman";
    public static final String GUARD_TOWER_ID    = "guardtower";
    public static final String HOME_ID           = "residence";
    public static final String LIBRARY_ID        = "library";
    public static final String LUMBERJACK_ID     = "lumberjack";
    public static final String MINER_ID          = "miner";
    public static final String SAWMILL_ID        = "sawmill";
    public static final String SHEPHERD_ID       = "shepherd";
    public static final String SIFTER_ID         = "sifter";
    public static final String SMELTERY_ID       = "smeltery";
    public static final String STONE_MASON_ID    = "stonemason";
    public static final String STONE_SMELTERY_ID = "stonesmeltery";
    public static final String SWINE_HERDER_ID   = "swineherder";
    public static final String TOWNHALL_ID       = "townhall";
    public static final String WAREHOUSE_ID      = "warehouse";
    public static final String POSTBOX_ID        = "postbox";
    public static final String FLORIST_ID        = "florist";
    public static final String ENCHANTER_ID      = "enchanter";
    public static final String UNIVERSITY_ID     = "university";
    public static final String HOSPITAL_ID       = "hospital";
    public static final String STASH_ID          = "stash";
    public static final String SCHOOL_ID         = "school";
    public static final String GLASSBLOWER_ID    = "glassblower";
    public static final String DYER_ID           = "dyer";
    public static final String FLETCHER_ID       = "fletcher";
    public static final String MECHANIC_ID       = "mechanic";
    public static final String PLANTATION_ID     = "plantation";
    public static final String TAVERN_ID         = "tavern";
    public static final String CONCRETE_ID       = "concretemixer";
    public static final String RABBIT_ID         = "rabbithutch";
    public static final String BEEKEEPER_ID      = "beekeeper";
    public static final String MYSTICAL_SITE_ID  = "mysticalsite";
    public static final String GRAVEYARD_ID      = "graveyard";
    public static final String NETHERWORKER_ID   = "netherworker";
    public static final String SIMPLE_QUARRY_ID  = "simplequarry";
    public static final String MEDIUM_QUARRY_ID  = "mediumquarry";
    public static final String LARGE_QUARRY_ID   = "largequarry";
    public static final String ALCHEMIST_ID      = "alchemist";
    public static final String KITCHEN_ID      = "kitchen";

    public static DeferredHolder<BuildingEntry, BuildingEntry> archery;
    public static DeferredHolder<BuildingEntry, BuildingEntry> bakery;
    public static DeferredHolder<BuildingEntry, BuildingEntry> barracks;
    public static DeferredHolder<BuildingEntry, BuildingEntry> barracksTower;
    public static DeferredHolder<BuildingEntry, BuildingEntry> blacksmith;
    public static DeferredHolder<BuildingEntry, BuildingEntry> builder;
    public static DeferredHolder<BuildingEntry, BuildingEntry> chickenHerder;
    public static DeferredHolder<BuildingEntry, BuildingEntry> combatAcademy;
    public static DeferredHolder<BuildingEntry, BuildingEntry> composter;
    public static DeferredHolder<BuildingEntry, BuildingEntry> cook;
    public static DeferredHolder<BuildingEntry, BuildingEntry> cowboy;
    public static DeferredHolder<BuildingEntry, BuildingEntry> crusher;
    public static DeferredHolder<BuildingEntry, BuildingEntry> deliveryman;
    public static DeferredHolder<BuildingEntry, BuildingEntry> farmer;
    public static DeferredHolder<BuildingEntry, BuildingEntry> fisherman;
    public static DeferredHolder<BuildingEntry, BuildingEntry> guardTower;
    public static DeferredHolder<BuildingEntry, BuildingEntry> home;
    public static DeferredHolder<BuildingEntry, BuildingEntry> library;
    public static DeferredHolder<BuildingEntry, BuildingEntry> lumberjack;
    public static DeferredHolder<BuildingEntry, BuildingEntry> miner;
    public static DeferredHolder<BuildingEntry, BuildingEntry> sawmill;
    public static DeferredHolder<BuildingEntry, BuildingEntry> shepherd;
    public static DeferredHolder<BuildingEntry, BuildingEntry> sifter;
    public static DeferredHolder<BuildingEntry, BuildingEntry> smeltery;
    public static DeferredHolder<BuildingEntry, BuildingEntry> stoneMason;
    public static DeferredHolder<BuildingEntry, BuildingEntry> stoneSmelter;
    public static DeferredHolder<BuildingEntry, BuildingEntry> swineHerder;
    public static DeferredHolder<BuildingEntry, BuildingEntry> townHall;
    public static DeferredHolder<BuildingEntry, BuildingEntry> wareHouse;
    public static DeferredHolder<BuildingEntry, BuildingEntry> postBox;
    public static DeferredHolder<BuildingEntry, BuildingEntry> florist;
    public static DeferredHolder<BuildingEntry, BuildingEntry> enchanter;
    public static DeferredHolder<BuildingEntry, BuildingEntry> university;
    public static DeferredHolder<BuildingEntry, BuildingEntry> hospital;
    public static DeferredHolder<BuildingEntry, BuildingEntry> stash;
    public static DeferredHolder<BuildingEntry, BuildingEntry> school;
    public static DeferredHolder<BuildingEntry, BuildingEntry> glassblower;
    public static DeferredHolder<BuildingEntry, BuildingEntry> dyer;
    public static DeferredHolder<BuildingEntry, BuildingEntry> fletcher;
    public static DeferredHolder<BuildingEntry, BuildingEntry> mechanic;
    public static DeferredHolder<BuildingEntry, BuildingEntry> plantation;
    public static DeferredHolder<BuildingEntry, BuildingEntry> tavern;
    public static DeferredHolder<BuildingEntry, BuildingEntry> concreteMixer;
    public static DeferredHolder<BuildingEntry, BuildingEntry> rabbitHutch;
    public static DeferredHolder<BuildingEntry, BuildingEntry> beekeeper;
    public static DeferredHolder<BuildingEntry, BuildingEntry> mysticalSite;
    public static DeferredHolder<BuildingEntry, BuildingEntry> graveyard;
    public static DeferredHolder<BuildingEntry, BuildingEntry> netherWorker;
    public static DeferredHolder<BuildingEntry, BuildingEntry> simpleQuarry;
    public static DeferredHolder<BuildingEntry, BuildingEntry> mediumQuarry;
    //public static DeferredHolder<BuildingEntry, BuildingEntry> largeQuarry;
    public static DeferredHolder<BuildingEntry, BuildingEntry> alchemist;
    public static DeferredHolder<BuildingEntry, BuildingEntry> kitchen;

    private ModBuildings()
    {
        throw new IllegalStateException("Tried to initialize: ModBuildings but this is a Utility class.");
    }
}
