name: Pull Request Management - Mark as Tested

on:
  issue_comment:
    types:
      - created

permissions:
  statuses: write
  pull-requests: read

jobs:
  mark-as-tested:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != null
    steps:
      - name: Set success status
        uses: actions/github-script@v8
        env:
          TRIGGER_PHRASE: '✅ I confirm my changes are tested'
        with:
          result-encoding: string
          retries: 3
          script: |
            const comment = context.payload.comment.body.trim();
            if (comment !== process.env.TRIGGER_PHRASE) return;

            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            if (pr.data.user.login !== context.payload.comment.user.login) return;

            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: pr.data.head.sha,
              state: 'success',
              context: 'Testing',
              description: 'Author has confirmed changes are tested',
            });