name: Pull Request Management - Testing status

on:
  pull_request_target:
    types:
      - synchronize
    paths:
      - src/**
      - '!src/main/resources/blueprints/**'

permissions:
  statuses: write

jobs:
  set-pending-status:
    runs-on: ubuntu-latest
    steps:
      - name: Set pending testing status
        uses: actions/github-script@v8
        with:
          result-encoding: string
          retries: 3
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.payload.pull_request.head.sha,
              state: 'pending',
              context: 'Testing',
              description: "Post `I confirm my changes are tested` as a comment to clear this",
            });